### PR TITLE
add logo source file

### LINKED ISSUE #15: Logo
Hi, @bcomnes :)

Inspiration of this Sunday.

Whats do you think about that : 
VHS-TAPE

### PR DESCRIPTION
**Pull request by tony-go**
Hi :) 

This PR contains the sketch file used for the logo :)

You'll find in this file all the previous versions.

EDITS:
Closes https://github.com/hyperdivision/vhs-tape/issues/15#issuecomment-525617239

### CODE REVIEW

**Comment by bcomnes** [comment]
Thank you @tony-go !

**Comment by bcomnes** [comment]
Ah man its really big, I'm going to revert the commit, and add it with LFS.

**Comment by bcomnes** [comment]
Ok rewrote the commit to use lfs, that should keep the repo size down.  Setting up npmignore next.

**Comment by tony-go** [comment]
Thanks :)  Sorry man, I never use LFS before. Thanks for the hint :)

**Comment by bcomnes** [comment]
Thats fine, generally I try to turn on lfs for any assets over a few megs.

**Pull request merged**
